package transform

import (
	"context"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	shimcompiler "github.com/microsoft/typescript-go/shim/compiler"
	"github.com/samchon/nestia/packages/core/native/plugin"
	"github.com/samchon/nestia/packages/core/native/transform/buildoutput"
	"github.com/samchon/ttsc/packages/ttsc/driver"
	typiaadapter "github.com/samchon/typia/packages/typia/native/adapter"
)

func runBuild(args []string) int {
	profile := os.Getenv("TTSC_NESTIA_PROFILE") != ""
	var totalStarted time.Time
	if profile {
		totalStarted = time.Now()
	}
	fs := flag.NewFlagSet("build", flag.ContinueOnError)
	fs.SetOutput(stderr)
	tsconfigPath := fs.String("tsconfig", "tsconfig.json", "path to tsconfig.json")
	cwdOverride := fs.String("cwd", "", "override the working directory")
	quiet := fs.Bool("quiet", true, "suppress the per-call diagnostic summary")
	verbose := fs.Bool("verbose", false, "print the per-call diagnostic summary")
	emit := fs.Bool("emit", false, "force emitted .js files")
	noEmit := fs.Bool("noEmit", false, "force analysis-only run with no file writes")
	outDir := fs.String("outDir", "", "override compilerOptions.outDir")
	manifestPath := fs.String("manifest", "", "write emitted file list as JSON")
	pluginsJSON := fs.String("plugins-json", "", "ordered ttsc plugin payload")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *emit && *noEmit {
		fmt.Fprintln(stderr, "ttsc-nestia build: --emit and --noEmit are mutually exclusive")
		return 2
	}
	if *verbose {
		*quiet = false
	}
	plan, err := plugin.ParsePlan(*pluginsJSON)
	if err != nil {
		fmt.Fprintf(stderr, "ttsc-nestia build: %v\n", err)
		return 2
	}

	cwd, ok := resolveCWD("ttsc-nestia build", *cwdOverride)
	if !ok {
		return 2
	}
	var started time.Time
	if profile {
		started = time.Now()
	}
	prog, diags, err := driver.LoadProgram(cwd, *tsconfigPath, driver.LoadProgramOptions{
		ForceEmit:   *emit,
		ForceNoEmit: *noEmit,
		OutDir:      *outDir,
	})
	profileBuildStep(profile, "load-program", started)
	if err != nil {
		fmt.Fprintf(stderr, "ttsc-nestia build: %v\n", err)
		return 2
	}
	if len(diags) > 0 {
		if prog != nil {
			prog.Close()
		}
		driver.WritePrettyDiagnostics(stderr, diags, cwd)
		return 2
	}
	if profile {
		started = time.Now()
	}
	if diags := prog.Diagnostics(); len(diags) > 0 {
		profileBuildStep(profile, "diagnostics", started)
		prog.Close()
		driver.WritePrettyDiagnostics(stderr, diags, cwd)
		return 2
	}
	profileBuildStep(profile, "diagnostics", started)

	shouldEmit := !prog.ParsedConfig.ParsedConfig.CompilerOptions.NoEmit.IsTrue()
	if !shouldEmit {
		// Plugin transformers are part of tsgo's emit pipeline. Reload with emit
		// enabled so check/noEmit traverses the same source set, then discard every
		// generated output below. The original program already proved the project's
		// diagnostics; diagnosing this private reload would reject valid analysis-
		// only options such as allowImportingTsExtensions.
		prog.Close()
		if profile {
			started = time.Now()
		}
		prog, diags, err = driver.LoadProgram(cwd, *tsconfigPath, driver.LoadProgramOptions{
			ForceEmit: true,
			OutDir:    *outDir,
		})
		profileBuildStep(profile, "load-transform-program", started)
		if err != nil {
			fmt.Fprintf(stderr, "ttsc-nestia build: %v\n", err)
			return 2
		}
		if len(diags) > 0 {
			if prog != nil {
				prog.Close()
			}
			driver.WritePrettyDiagnostics(stderr, diags, cwd)
			return 2
		}
	}
	defer prog.Close()
	releaseTypiaRegistries := registerTypiaDefaultLibraryClassifier(prog)
	defer releaseTypiaRegistries()
	publication := buildoutput.New(buildoutput.Options{
		TSConfig: *tsconfigPath, CWD: cwd, Manifest: *manifestPath,
		Core: plan.Core, SDK: plan.SDK, Typia: plan.Typia,
		Emit: shouldEmit, Quiet: *quiet,
	}, stdout, driver.DefaultWriteFile)
	// Publication owns all generated bytes until actual diagnostics accept them.
	// Every earlier return terminates this session without committing its buffer.
	defer publication.Finish(false)

	// AST-integration emit: typia's per-file transformer and @nestia/core's own
	// per-file transformer both run inside tsgo's emit pipeline (sharing the
	// EmitContext), so they return AST and tsgo's module-transform aliases the
	// namespace imports they inject. This is the only emit path.
	transformDiags := []Diagnostic{}
	addDiagnostic := func(diag Diagnostic) {
		transformDiags = append(transformDiags, diag)
	}
	if profile {
		started = time.Now()
	}
	newPathsRewriter(prog).applyAll(prog.SourceFiles())
	profileBuildStep(profile, "paths-rewrite", started)

	typiaTransform := nestiaTypiaNodeTransform(prog, readTypiaPluginOptions(plan), addDiagnostic)
	coreTransform := nestiaCoreNodeTransform(prog, plan, addDiagnostic)

	// Statically linked contributors (e.g. the @nestia/sdk OperationMetadata
	// pass) run their per-file emit transformer in the same EmitContext after
	// typia and core, mirroring the `transform` subcommand. Without this the
	// build/emit path silently drops a contributor that opted in through its own
	// flag (NESTIA_SDK_TRANSFORM) rather than the ttsc linked-plugin registry, so
	// its metadata never reaches the emitted JavaScript.
	contributorTransforms, contributorDiags := collectContributorEmitTransforms(prog, plan)
	if len(contributorDiags) > 0 {
		WriteTypiaTransformDiagnostics(stderr, contributorDiags, cwd)
		return 3
	}
	transforms := append([]driver.PluginTransform{typiaTransform, coreTransform}, contributorTransforms...)

	writeFile := shimcompiler.WriteFile(func(fileName, text string, data *shimcompiler.WriteFileData) error {
		_ = data
		publication.Write(fileName, text)
		return nil
	})

	// Declaration emit: ttsc delegates the whole emit of a transform-plugin
	// package to this host, but EmitWithPluginTransformers writes only .js. A
	// library package (e.g. @nestia/core itself) ships .d.ts, so emit the
	// declarations here with tsgo's standard declaration emitter. The typia /
	// core runtime transforms never change the public type surface, so the
	// declarations are taken from the pristine program — done before the JS
	// transform runs so it reads the un-mutated AST.
	if shouldEmit && prog.ParsedConfig.ParsedConfig.CompilerOptions.Declaration.IsTrue() {
		if profile {
			started = time.Now()
		}
		emitDeclarations(prog, writeFile)
		profileBuildStep(profile, "declaration-emit", started)
	}

	if profile {
		started = time.Now()
	}
	eDiags, err := prog.EmitWithPluginTransformers(transforms, writeFile)
	profileBuildStep(profile, "emit-total", started)
	if err != nil {
		fmt.Fprintf(stderr, "ttsc-nestia build: emit failed: %v\n", err)
		return 3
	}
	emitHasError := false
	for _, d := range eDiags {
		fmt.Fprintln(stderr, "  -", d.String())
		if d.IsError() {
			emitHasError = true
		}
	}
	if len(transformDiags) > 0 {
		WriteTypiaTransformDiagnostics(stderr, transformDiags, cwd)
		return 3
	}
	if emitHasError {
		return 3
	}
	if err := publication.Finish(true); err != nil {
		fmt.Fprintf(stderr, "ttsc-nestia build: %v\n", err)
		return 3
	}

	profileBuildStep(profile, "total", totalStarted)
	return 0
}

// emitDeclarations runs tsgo's standard declaration emitter for the program.
// tsgo's MarkLinkedReferences pass can nil-panic on some cross-module reference
// shapes (e.g. a nestia.config.ts that calls NestFactory.create, compiled by the
// SDK config loader only to be require()d). The .js the caller needs is emitted
// separately by EmitWithPluginTransformers, so recover and skip the .d.ts for
// this run instead of aborting the whole build.
func emitDeclarations(prog *driver.Program, writeFile shimcompiler.WriteFile) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Fprintf(stderr, "ttsc-nestia build: declaration emit skipped (%v)\n", r)
		}
	}()
	dts := prog.TSProgram.Emit(context.Background(), shimcompiler.EmitOptions{
		EmitOnly:  shimcompiler.EmitOnlyDts,
		WriteFile: writeFile,
	})
	if dts != nil && dts.EmitSkipped {
		fmt.Fprintln(stderr, "ttsc-nestia build: declaration emit skipped")
	}
}

func runCheck(args []string) int {
	return runBuild(append([]string{"--noEmit"}, args...))
}

// Diagnostic is one transform error: its file, line and column when known, its code, and its message.
//
// @evidence contracts/common.md#principled-implementation The record carries what the diagnostic line and the compiler envelope need, and a zero line marks a diagnostic without a position.
// @evidence contracts/common.md#clear-and-simple-design A five-field record with one formatting method.
// @evidence contracts/common.md#prohibited-implementation-shortcuts The values come from the transforms that report them.
// @evidence contracts/common.md#meaningful-documentation The comment names the fields and the meaning of an absent position.
type Diagnostic struct {
	File    string
	Line    int
	Column  int
	Code    string
	Message string
}

// String formats the diagnostic as `file:line:column - error TS(code): message`, with the file made relative to `cwd` when possible, and without the position when the line is unknown.
//
// @evidence contracts/common.md#principled-implementation The path is made relative with `filepath.Rel` and the position part is printed only for a positive line, which is the same shape as every other nestia and typia diagnostic.
// @evidence contracts/common.md#clear-and-simple-design One function with two format strings.
// @evidence contracts/common.md#prohibited-implementation-shortcuts The shape is the protocol that ttsc reads from stderr, not a test-specific format.
// @evidence contracts/common.md#meaningful-documentation The comment states the two formats and the relative path rule.
func (d Diagnostic) String(cwd string) string {
	file := d.File
	if rel, err := filepath.Rel(cwd, file); err == nil {
		file = rel
	}
	if d.Line > 0 {
		return fmt.Sprintf("%s:%d:%d - error TS(%s): %s", file, d.Line, d.Column, d.Code, d.Message)
	}
	return fmt.Sprintf("%s - error TS(%s): %s", file, d.Code, d.Message)
}

// WriteTypiaTransformDiagnostics writes each diagnostic on its own line to the writer, with files relative to `cwd`.
//
// @evidence contracts/common.md#principled-implementation Each diagnostic is written by its own `String`, one per line in the given order, so the output is the concatenation of the formatted diagnostics.
// @evidence contracts/common.md#clear-and-simple-design One loop over one formatter.
// @evidence contracts/common.md#prohibited-implementation-shortcuts It writes what it is given, without filtering or reordering.
// @evidence contracts/common.md#meaningful-documentation The comment states the format and the ordering.
func WriteTypiaTransformDiagnostics(out io.Writer, diagnostics []Diagnostic, cwd string) {
	for _, diag := range diagnostics {
		fmt.Fprintln(out, diag.String(cwd))
	}
}

func profileBuildStep(enabled bool, name string, started time.Time) {
	if enabled {
		profileBuildDuration(enabled, name, time.Since(started))
	}
}
func profileBuildDuration(enabled bool, name string, elapsed time.Duration) {
	if enabled {
		fmt.Fprintf(stderr, "ttsc-nestia profile: %s=%s\n", name, elapsed)
	}
}

// readTypiaPluginOptions takes typia's transform options from the resolved plugin
// payload ttsc hands this binary, not from the text of one tsconfig file.
//
// The file is the wrong source twice over. It is only the *entry* of an `extends`
// chain, so an option declared in a base was invisible — the compile then
// succeeded with a weaker validator than the project asked for, and nothing said
// so. And a text scan matches anywhere, so `"numeric": true` inside a comment or
// an unrelated object turned the option on for a project that never set it. ttsc
// has already resolved the whole chain by the time it builds --plugins-json.
//
// Options are read from every plugin entry, with typia's own entry winning, so a
// project that sets them on the composing @nestia/core entry keeps working.
func readTypiaPluginOptions(plan plugin.Plan) typiaadapter.PluginOptions {
	options := typiaadapter.PluginOptions{}
	apply := func(entry plugin.Entry) {
		if value, ok := entry.BoolConfig("functional"); ok {
			options.Functional = value
		}
		if value, ok := entry.BoolConfig("numeric"); ok {
			options.Numeric = value
		}
		if value, ok := entry.BoolConfig("finite"); ok {
			options.Finite = value
		}
		// `undefined` is tri-state: an explicit false must stay distinguishable
		// from an absent option, so copy into a fresh variable rather than
		// aliasing the closure's parameter.
		if value, ok := entry.BoolConfig("undefined"); ok {
			flag := value
			options.Undefined = &flag
		}
	}
	for _, entry := range plan.Entries {
		if entry.Kind() != "typia" {
			apply(entry)
		}
	}
	for _, entry := range plan.Entries {
		if entry.Kind() == "typia" {
			apply(entry)
		}
	}
	return options
}

func resolveCWD(label string, cwdOverride string) (string, bool) {
	if cwdOverride != "" {
		return cwdOverride, true
	}
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(stderr, "%s: cwd: %v\n", label, err)
		return "", false
	}
	return cwd, true
}
