/**
 * @packageDocumentation
 * @module api.functional.api.v1.articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as comments from "./comments";