import { INestiaConfig } from "@nestia/sdk";

export const NESTIA_CONFIG: INestiaConfig = {
  input: [
    "features/body-error-generic/src",
    "features/body-error-json/src",
    "features/headers-error-array/src",
    "features/headers-error-atomic/src",
    "features/headers-error-property-array/src",
    "features/headers-error-property-nullable/src",
    "features/headers-error-property-single/src",
    "features/headers-error-union-object/src",
    "features/headers-error-union-property/src",
    "features/param-error-array/src",
    "features/param-error-generic/src",
    "features/param-error-native/src",
    "features/param-error-object/src",
    "features/param-error-union/src",
    "features/param-error-union-literal/src",
    "features/plain-error-any/src",
    "features/plain-error-nullable/src",
    "features/plain-error-number/src",
    "features/plain-error-object/src",
    "features/query-error-array/src",
    "features/query-error-atomic/src",
    "features/query-error-generic/src",
    "features/query-error-native/src",
    "features/query-error-union-array/src",
    "features/query-error-union-literal/src",
    "features/query-error-union-object/src",
    "features/query-error-union-property/src",
    "features/route-error-generic/src",
    "features/route-error-json/src",
    "features/websocket-error-invalid-acceptor/src",
    "features/websocket-error-invalid-driver/src",
    "features/websocket-error-invalid-parameter/src",
    "features/websocket-error-no-acceptor/src",
  ],
  output: ".tmp-error-diagnostics",
};
export default NESTIA_CONFIG;
