import { INestiaConfig } from "@nestia/sdk";

export const NESTIA_CONFIG: INestiaConfig = {
  input: [
    "features/body-error-generic/src/controllers",
    "features/body-error-json/src/controllers",
    "features/headers-error-array/src/controllers",
    "features/headers-error-atomic/src/controllers",
    "features/headers-error-property-array/src/controllers",
    "features/headers-error-property-nullable/src/controllers",
    "features/headers-error-property-single/src/controllers",
    "features/headers-error-union-object/src/controllers",
    "features/headers-error-union-property/src/controllers",
    "features/param-error-array/src/controllers",
    "features/param-error-generic/src/controllers",
    "features/param-error-native/src/controllers",
    "features/param-error-object/src/controllers",
    "features/param-error-union/src/controllers",
    "features/param-error-union-literal/src/controllers",
    "features/plain-error-any/src/controllers",
    "features/plain-error-nullable/src/controllers",
    "features/plain-error-number/src/controllers",
    "features/plain-error-object/src/controllers",
    "features/query-error-array/src/controllers",
    "features/query-error-atomic/src/controllers",
    "features/query-error-generic/src/controllers",
    "features/query-error-native/src/controllers",
    "features/query-error-union-array/src/controllers",
    "features/query-error-union-literal/src/controllers",
    "features/query-error-union-object/src/controllers",
    "features/query-error-union-property/src/controllers",
    "features/route-error-generic/src/controllers",
    "features/route-error-json/src/controllers",
    "features/websocket-error-invalid-acceptor/src/controllers",
    "features/websocket-error-invalid-driver/src/controllers",
    "features/websocket-error-invalid-parameter/src/controllers",
    "features/websocket-error-no-acceptor/src/controllers",
  ],
  output: ".tmp-error-diagnostics",
};
export default NESTIA_CONFIG;
