import { SyntaxKind, factory } from "@ttsc/factory";
import { OpenApi } from "@typia/interface";
import { IPointer } from "tstl";

import ts from "../internal/ts";
import { INestiaMigrateConfig } from "../structures/INestiaMigrateConfig";
import { FilePrinter } from "../utils/FilePrinter";
import { MapUtil } from "../utils/MapUtil";
import { StringUtil } from "../utils/StringUtil";
import { NestiaMigrateImportProgrammer } from "./NestiaMigrateImportProgrammer";
import { NestiaMigrateSchemaProgrammer } from "./NestiaMigrateSchemaProgrammer";

export namespace NestiaMigrateDtoProgrammer {
  export interface IModule {
    name: string;
    children: Map<string, IModule>;
    programmer:
      | null
      | ((importer: NestiaMigrateImportProgrammer) => ts.TypeAliasDeclaration);
  }

  export const compose = (props: {
    config: INestiaMigrateConfig;
    components: OpenApi.IComponents;
  }): Map<string, IModule> => {
    const dict: Map<string, IModule> = new Map();
    for (const [key, value] of Object.entries(props.components.schemas ?? {})) {
      const emendedKey: string = key
        .split("/")
        .filter((str) => str.length !== 0)
        .map(StringUtil.escapeNonVariable)
        .join("");
      prepare(dict)(emendedKey)((importer) =>
        writeAlias(props.config)(props.components)(importer)(emendedKey, value),
      );
    }
    return dict;
  };

  const prepare =
    (dict: Map<string, IModule>) =>
    (name: string) =>
    (
      programmer: (
        importer: NestiaMigrateImportProgrammer,
      ) => ts.TypeAliasDeclaration,
    ) => {
      const accessors: string[] = name.split(".");
      const modulo: IPointer<IModule> = { value: null! };

      accessors.forEach((acc, i) => {
        modulo.value = MapUtil.take(dict)(acc)(() => ({
          name: acc,
          children: new Map(),
          programmer: null,
        }));
        if (i === accessors.length - 1) modulo.value.programmer = programmer;
        dict = modulo.value.children;
      });
      return modulo!;
    };

  const writeAlias =
    (config: INestiaMigrateConfig) =>
    (components: OpenApi.IComponents) =>
    (importer: NestiaMigrateImportProgrammer) =>
    (key: string, value: OpenApi.IJsonSchema) =>
      FilePrinter.description(
        factory.createTypeAliasDeclaration(
          [factory.createToken(SyntaxKind.ExportKeyword)],
          key.split(".").at(-1)!,
          [],
          NestiaMigrateSchemaProgrammer.write({
            components,
            importer,
            schema: value,
          }),
        ),
        writeComment(config)(value, key.indexOf(".") === -1),
      );
}

const writeComment =
  (config: INestiaMigrateConfig) =>
  (schema: OpenApi.IJsonSchema, top: boolean): string => {
    // PLUGIN PROPERTIES (x-) AS JSDOC TAGS
    //
    // Mirror NestiaMigrateSchemaProgrammer: emit every `x-` extension property
    // whose value is a primitive as an `@x-key value` JSDoc tag, so the plugin
    // metadata survives the swagger -> DTO round trip.
    const plugins: string[] = [];
    for (const [key, value] of Object.entries(schema))
      if (key.startsWith("x-") && isExtensionValue(value))
        plugins.push(`@${key} ${String(value)}`);
    return [
      ...(schema.description?.length ? [schema.description] : []),
      ...(schema.description?.length &&
      (schema.title !== undefined ||
        schema.deprecated === true ||
        plugins.length !== 0)
        ? [""]
        : []),
      ...(schema.title !== undefined ? [`@title ${schema.title}`] : []),
      ...(schema.deprecated === true ? [`@deprecated`] : []),
      ...plugins,
      ...(top
        ? [
            `@${config.author?.tag ?? "nestia"} ${config.author?.value ?? "Generated by Nestia - https://github.com/samchon/nestia"}`,
          ]
        : []),
    ].join("\n");
  };

const isExtensionValue = (value: unknown): value is boolean | number | string =>
  typeof value === "boolean" ||
  typeof value === "number" ||
  typeof value === "string";
