packages:
  - 'benchmark'
  - 'config'
  - 'packages/*'
  - 'tests/*'

catalogs:
  nestjs:
    '@nestjs/common': &nestjs ^11.1.6
    '@nestjs/core': *nestjs
    '@nestjs/platform-express': *nestjs
    '@nestjs/platform-fastify': *nestjs
    rxjs: ^7.1.0
  samchon:
    typia: &typia ^13.0.2
    '@typia/interface': *typia
    '@typia/utils': *typia
    tgrid: ^1.2.1
    tstl: ^3.0.0
  utils:
    '@types/node': ^25.3.3
    '@types/uuid': ^11.0.0
    cross-env: ^10.1.0
    rimraf: ^6.1.3
    uuid: ^13.0.0
  typescript:
    ttsc: &ttsc ^0.18.4
    '@ttsc/factory': *ttsc
    '@ttsc/unplugin': *ttsc
    '@trivago/prettier-plugin-sort-imports': ^4.3.0
    prettier: ^3.8.1
    prettier-plugin-jsdoc: ^1.8.0
    typescript: ^7.0.2
  modelcontextprotocol:
    '@modelcontextprotocol/sdk': ^1.18.0
  rolldown:
    rolldown: ^1.1.5
