import fs from "fs";
import ts from "typescript";

import { INestiaConfig } from "../../INestiaConfig";
import { IRoute } from "../../structures/IRoute";
import { FormatUtil } from "../../utils/FormatUtil";
import { ImportDictionary } from "../../utils/ImportDictionary";
import { MapUtil } from "../../utils/MapUtil";
import { SdkRouteDirectory } from "./SdkRouteDirectory";
import { SdkRouteProgrammer } from "./SdkRouteProgrammer";

export namespace SdkFileProgrammer {
  /* ---------------------------------------------------------
        CONSTRUCTOR
    --------------------------------------------------------- */
  export const generate =
    (config: INestiaConfig) =>
    async (routeList: IRoute[]): Promise<void> => {
      // CONSTRUCT FOLDER TREE
      const root: SdkRouteDirectory = new SdkRouteDirectory(null, "functional");
      for (const route of routeList) emplace(root)(route);

      // ITERATE FILES
      await iterate(config)(root)(config.output + "/functional");
    };

  const emplace =
    (directory: SdkRouteDirectory) =>
    (route: IRoute): void => {
      // OPEN DIRECTORIES
      for (const key of route.accessors.slice(0, -1)) {
        directory = MapUtil.take(
          directory.children,
          key,
          () => new SdkRouteDirectory(directory, key),
        );
      }

      // ADD ROUTE
      directory.routes.push(route);
    };

  /* ---------------------------------------------------------
        FILE ITERATOR
    --------------------------------------------------------- */
  const iterate =
    (config: INestiaConfig) =>
    (directory: SdkRouteDirectory) =>
    async (outDir: string): Promise<void> => {
      // CREATE A NEW DIRECTORY
      try {
        await fs.promises.mkdir(outDir);
      } catch {}

      // ITERATE CHILDREN
      const statements: ts.Statement[] = [];
      for (const [key, value] of directory.children) {
        await iterate(config)(value)(`${outDir}/${key}`);
        statements.push(
          ts.factory.createExportDeclaration(
            undefined,
            false,
            ts.factory.createNamespaceExport(ts.factory.createIdentifier(key)),
            ts.factory.createStringLiteral(`./${key}`),
            undefined,
          ),
        );
      }
      if (statements.length && directory.routes.length)
        statements.push(FormatUtil.enter());

      // ITERATE ROUTES
      const importer: ImportDictionary = new ImportDictionary(
        `${outDir}/index.ts`,
      );
      if (
        config.simulate === true &&
        directory.routes.some((r) => !!r.parameters.length)
      )
        importer.internal({
          file: `${config.output}/utils/NestiaSimulator.ts`,
          instance: "NestiaSimulator",
          type: false,
        });
      directory.routes.forEach((route, i) => {
        if (config.clone !== true)
          for (const tuple of route.imports)
            for (const instance of tuple[1])
              importer.internal({
                file: tuple[0],
                instance,
                type: true,
              });
        statements.push(
          ...SdkRouteProgrammer.generate(config)(importer)(route),
        );
        if (i !== directory.routes.length - 1)
          statements.push(FormatUtil.enter());
      });

      // FINALIZE THE CONTENT
      if (directory.routes.length !== 0)
        statements.push(
          ...importer.toStatements(outDir),
          ...(!importer.empty() && statements.length
            ? [FormatUtil.enter()]
            : []),
          ...statements.splice(0, statements.length),
        );

      const script: string =
        "/**\n" +
        " * @packageDocumentation\n" +
        ` * @module ${directory.module}\n` +
        " * @nestia Generated by Nestia - https://github.com/samchon/nestia \n" +
        " */\n" +
        "//================================================================\n" +
        ts
          .createPrinter()
          .printFile(
            ts.factory.createSourceFile(
              statements,
              ts.factory.createToken(ts.SyntaxKind.EndOfFileToken),
              ts.NodeFlags.None,
            ),
          );
      await fs.promises.writeFile(
        importer.file,
        await FormatUtil.beautify(script),
        "utf8",
      );
    };
}
