import { type Node } from "@ttsc/factory";
import { IJsDocTagInfo } from "typia";

import { INestiaProject } from "../../structures/INestiaProject";
import { ITypedHttpRoute } from "../../structures/ITypedHttpRoute";
import { FilePrinter } from "./FilePrinter";
import { ImportDictionary } from "./ImportDictionary";
import { SdkHttpFunctionProgrammer } from "./SdkHttpFunctionProgrammer";
import { SdkHttpNamespaceProgrammer } from "./SdkHttpNamespaceProgrammer";
import { SdkHttpParameterProgrammer } from "./SdkHttpParameterProgrammer";

/**
 * Writes an HTTP route into the SDK: its function and its namespace.
 *
 * @evidence contracts/common.md#principled-implementation The namespace pairs the two declarations and describes the function.
 * @evidence contracts/common.md#clear-and-simple-design One public function and one description helper.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts The description is from the route's own comment.
 * @evidence contracts/common.md#meaningful-documentation The comment states what the declaration produces and its result.
 */
export namespace SdkHttpRouteProgrammer {
  /**
   * Returns the function and the namespace of a route, the function carrying
   * the route's description, `@param`, and exception tags, and a `@nestia`
   * postfix.
   *
   * @evidence contracts/common.md#principled-implementation The two nodes share the identifiers of one decision.
   * @evidence contracts/common.md#clear-and-simple-design One function.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts The description keeps the names the function declares.
   * @evidence contracts/common.md#meaningful-documentation The comment states what the declaration produces and its result.
   */
  export const write =
    (project: INestiaProject) =>
    (importer: ImportDictionary) =>
    (route: ITypedHttpRoute): Node[] => [
      FilePrinter.description(
        SdkHttpFunctionProgrammer.write(project)(importer)(route),
        describe(project, route),
      ),
      SdkHttpNamespaceProgrammer.write(project)(importer)(route),
    ];

  const describe = (
    project: INestiaProject,
    route: ITypedHttpRoute,
  ): string => {
    const names: SdkHttpParameterProgrammer.INames =
      SdkHttpParameterProgrammer.getNames({ project, route });
    // MAIN DESCRIPTION
    const descriptionComments: string[] = route.description
      ? route.description.split("\n")
      : [];
    const tagComments: string[] = [];

    // PARAMETERS
    for (const p of SdkHttpParameterProgrammer.getSignificant(route, true)) {
      const description: string | undefined =
        p.description ??
        p.jsDocTags.find((tag) => tag.name === "description")?.text?.[0]
          ?.text ??
        route.jsDocTags
          .find((tag) => tag.name === "param" && tag.text?.[0]?.text === p.name)
          ?.text?.find((e) => e.kind === "text")?.text;
      if (!description?.length) continue;

      // the name the SDK function declares, which yields on a collision
      const name: string =
        project.config.keyword === true
          ? `${names.props}.${p.name}`
          : names.parameter(p);
      tagComments.push(FilePrinter.jsDocTag(`param ${name}`, description));
    }

    // COMMENT TAGS
    const tags: IJsDocTagInfo[] = route.jsDocTags.filter(
      (tag) => tag.name !== "param",
    );
    if (tags.length !== 0) {
      const content: string[] = tags.map((t) =>
        FilePrinter.jsDocTag(t.name, t.text?.map((e) => e.text).join("") ?? ""),
      );
      tagComments.push(...new Set(content));
    }

    // EXCEPTIONS
    for (const [key, value] of Object.entries(route.exceptions)) {
      if (
        tagComments.some(
          (str) =>
            str.startsWith(`@throw ${key}`) || str.startsWith(`@throws ${key}`),
        )
      )
        continue;
      tagComments.push(
        value.description?.length
          ? `@throws ${key} ${value.description.split("\n")[0]}`
          : `@throws ${key}`,
      );
    }

    // POSTFIX
    return [
      ...descriptionComments,
      ...(descriptionComments.length && tagComments.length ? [""] : []),
      ...tagComments,
      ...(descriptionComments.length && tagComments.length ? [""] : []),
      // the public name, kept by a route declared under a local one
      `@controller ${route.controller.class.name}.${route.key}`,
      `@path ${route.method} ${route.path}`,
      `@accessor api.functional.${route.accessor.join(".")}`,
      `@nestia Generated by Nestia - https://github.com/samchon/nestia`,
    ].join("\n");
  };
}
