import {
  type Expression,
  NodeFlags,
  type Statement,
  SyntaxKind,
  type TypeNode,
  factory,
} from "@ttsc/factory";

import { IdentifierFactory } from "../../factories/IdentifierFactory";
import { INestiaProject } from "../../structures/INestiaProject";
import { ITypedWebSocketRoute } from "../../structures/ITypedWebSocketRoute";
import { FilePrinter } from "./FilePrinter";
import { ImportDictionary } from "./ImportDictionary";
import { SdkImportWizard } from "./SdkImportWizard";
import { SdkWebSocketNamespaceProgrammer } from "./SdkWebSocketNamespaceProgrammer";
import { SdkWebSocketParameterProgrammer } from "./SdkWebSocketParameterProgrammer";

export namespace SdkWebSocketRouteProgrammer {
  export const write =
    (project: INestiaProject) =>
    (importer: ImportDictionary) =>
    (route: ITypedWebSocketRoute): Statement[] => [
      FilePrinter.description(
        writeFunction(project)(importer)(route),
        writeDescription(project, route),
      ),
      SdkWebSocketNamespaceProgrammer.write(project)(importer)(route),
    ];

  const writeDescription = (
    project: INestiaProject,
    route: ITypedWebSocketRoute,
  ): string => {
    // MAIN DESCRIPTION
    const comments: string[] = route.description
      ? route.description.split("\n")
      : [];

    // COMMENT TAGS, each `@param` naming what the SDK function declares,
    // which yields on a collision
    const names: SdkWebSocketParameterProgrammer.INames =
      SdkWebSocketParameterProgrammer.getNames({ project, route });
    const declared = (name: string | undefined): string | null => {
      const path = route.pathParameters.find((p) => p.name === name);
      const key: string | null =
        path !== undefined
          ? project.config.keyword === true
            ? path.name
            : names.parameter(path)
          : route.query !== null && route.query.name === name
            ? names.query
            : null;
      return key === null
        ? null
        : project.config.keyword === true
          ? `${names.props}.${key}`
          : key;
    };
    const tags: string[] = route.jsDocTags
      .map((tag): string | null => {
        if (tag.name !== "param")
          return FilePrinter.jsDocTag(
            tag.name,
            tag.text?.map((e) => e.text).join("") ?? "",
          );
        const name: string | null = declared(tag.text?.[0]?.text);
        return name === null
          ? null
          : FilePrinter.jsDocTag(
              `param ${name}`,
              tag.text?.find((e) => e.kind === "text")?.text ?? "",
            );
      })
      .filter((tag): tag is string => tag !== null);
    // apart from the description, when there is one
    if (tags.length !== 0)
      comments.push(...(comments.length !== 0 ? [""] : []), ...new Set(tags));

    // POSTFIX
    if (!!comments.length) comments.push("");
    comments.push(
      // the public name, kept by a route declared under a local one
      `@controller ${route.controller.class.name}.${route.accessor.at(-1) ?? route.name}`,
      `@path ${route.path}`,
      `@nestia Generated by Nestia - https://github.com/samchon/nestia`,
    );
    return comments.join("\n");
  };

  const writeFunction =
    (project: INestiaProject) =>
    (importer: ImportDictionary) =>
    (route: ITypedWebSocketRoute): Statement => {
      const names: SdkWebSocketParameterProgrammer.INames =
        SdkWebSocketParameterProgrammer.getNames({ project, route });
      return factory.createFunctionDeclaration(
        [
          factory.createModifier(SyntaxKind.ExportKeyword),
          factory.createModifier(SyntaxKind.AsyncKeyword),
        ],
        undefined,
        route.name,
        undefined,
        [
          IdentifierFactory.parameter(
            names.connection,
            factory.createTypeReferenceNode(
              SdkImportWizard.IConnection(importer),
              [factory.createTypeReferenceNode(`${route.name}.Header`)],
            ),
          ),
          ...SdkWebSocketParameterProgrammer.getParameterDeclarations({
            project,
            route,
            provider: true,
            prefix: true,
          }),
        ],
        factory.createTypeReferenceNode("Promise", [
          factory.createTypeReferenceNode(`${route.name}.Output`),
        ]),
        factory.createBlock(
          writeFunctionBody(project)(importer)(route)(names),
          true,
        ),
      );
    };

  const writeFunctionBody =
    (project: INestiaProject) =>
    (importer: ImportDictionary) =>
    (route: ITypedWebSocketRoute) =>
    (names: SdkWebSocketParameterProgrammer.INames): Statement[] => {
      return [
        local(names.url)(factory.createTypeReferenceNode("string"))(
          joinPath(
            names.connection,
            factory.createCallExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier(route.name),
                "path",
              ),
              [],
              project.config.keyword === true &&
                SdkWebSocketParameterProgrammer.isPathEmpty(route) === false
                ? [factory.createIdentifier(names.props)]
                : SdkWebSocketParameterProgrammer.getEntries({
                    project,
                    route,
                    provider: false,
                    prefix: true,
                  }).map((p) => factory.createIdentifier(p.key)),
            ),
          ),
        ),
        local(names.connector)(
          factory.createTypeReferenceNode(
            importer.external({
              declaration: false,
              file: "tgrid",
              type: "element",
              name: "WebSocketConnector",
            }),
            [
              factory.createTypeReferenceNode(`${route.name}.Header`),
              factory.createTypeReferenceNode(`${route.name}.Provider`),
              factory.createTypeReferenceNode(`${route.name}.Listener`),
            ],
          ),
        )(
          factory.createNewExpression(
            factory.createIdentifier(
              importer.external({
                declaration: false,
                file: "tgrid",
                type: "element",
                name: "WebSocketConnector",
              }),
            ),
            undefined,
            [
              factory.createAsExpression(
                factory.createBinaryExpression(
                  factory.createPropertyAccessExpression(
                    factory.createIdentifier(names.connection),
                    "headers",
                  ),
                  factory.createToken(SyntaxKind.QuestionQuestionToken),
                  factory.createObjectLiteralExpression([], false),
                ),
                factory.createKeywordTypeNode(SyntaxKind.AnyKeyword),
              ),
              names.access(names.provider),
            ],
          ),
        ),
        factory.createExpressionStatement(
          factory.createAwaitExpression(
            factory.createCallExpression(
              factory.createPropertyAccessExpression(
                factory.createIdentifier(names.connector),
                "connect",
              ),
              undefined,
              [factory.createIdentifier(names.url)],
            ),
          ),
        ),
        local(names.driver)(
          factory.createTypeReferenceNode(
            importer.external({
              declaration: true,
              file: "tgrid",
              type: "element",
              name: "Driver",
            }),
            [factory.createTypeReferenceNode(`${route.name}.Listener`)],
          ),
        )(
          factory.createCallExpression(
            factory.createPropertyAccessExpression(
              factory.createIdentifier(names.connector),
              "getDriver",
            ),
            undefined,
            undefined,
          ),
        ),
        factory.createReturnStatement(
          factory.createObjectLiteralExpression(
            [
              writeOutputMember("connector", names.connector),
              writeOutputMember("driver", names.driver),
              factory.createPropertyAssignment(
                factory.createIdentifier("reconnect"),
                factory.createArrowFunction(
                  [factory.createToken(SyntaxKind.AsyncKeyword)],
                  undefined,
                  [],
                  undefined,
                  factory.createToken(SyntaxKind.EqualsGreaterThanToken),
                  factory.createAwaitExpression(
                    factory.createCallExpression(
                      factory.createPropertyAccessExpression(
                        factory.createIdentifier(names.connector),
                        factory.createIdentifier("connect"),
                      ),
                      undefined,
                      [factory.createIdentifier(names.url)],
                    ),
                  ),
                ),
              ),
            ],
            true,
          ),
        ),
      ];
    };
}

/** A member of the returned `Output`, shorthand when its local has its name. */
const writeOutputMember = (key: string, local: string) =>
  key === local
    ? factory.createShorthandPropertyAssignment(key)
    : factory.createPropertyAssignment(key, factory.createIdentifier(local));

const local = (name: string) => (type: TypeNode) => (expression: Expression) =>
  factory.createVariableStatement(
    [],
    factory.createVariableDeclarationList(
      [factory.createVariableDeclaration(name, undefined, type, expression)],
      NodeFlags.Const,
    ),
  );

const joinPath = (connection: string, caller: Expression) =>
  factory.createTemplateExpression(factory.createTemplateHead("", ""), [
    factory.createTemplateSpan(
      factory.createConditionalExpression(
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createPropertyAccessExpression(
              factory.createIdentifier(connection),
              factory.createIdentifier("host"),
            ),
            factory.createIdentifier("endsWith"),
          ),
          undefined,
          [factory.createStringLiteral("/")],
        ),
        factory.createToken(SyntaxKind.QuestionToken),
        factory.createCallExpression(
          factory.createPropertyAccessExpression(
            factory.createPropertyAccessExpression(
              factory.createIdentifier(connection),
              factory.createIdentifier("host"),
            ),
            factory.createIdentifier("substring"),
          ),
          undefined,
          [
            factory.createNumericLiteral("0"),
            factory.createBinaryExpression(
              factory.createPropertyAccessExpression(
                factory.createPropertyAccessExpression(
                  factory.createIdentifier(connection),
                  factory.createIdentifier("host"),
                ),
                factory.createIdentifier("length"),
              ),
              factory.createToken(SyntaxKind.MinusToken),
              factory.createNumericLiteral("1"),
            ),
          ],
        ),
        factory.createToken(SyntaxKind.ColonToken),
        factory.createPropertyAccessExpression(
          factory.createIdentifier(connection),
          factory.createIdentifier("host"),
        ),
      ),
      factory.createTemplateMiddle(""),
    ),
    factory.createTemplateSpan(caller, factory.createTemplateTail("")),
  ]);
