package test

import "testing"

// TestTransformBodyAssertPruneUsesAssertValidator verifies the @TypedBody
// generator routes `validate: "assertPrune"` through the misc
// MiscAssertPruneProgrammer while recording `type: "assert"`.
//
// The prune family strips excess properties from the value instead of rejecting
// them; assertPrune is the throwing variant. It is generated by a distinct misc
// programmer, so a regression in helper selection would silently fall back to a
// non-pruning validator and let extra properties through.
//
//  1. Transform the body controller with validate "assertPrune".
//  2. Read the emitted --out source.
//  3. Assert the validator metadata records the assert type.
func TestTransformBodyAssertPruneUsesAssertValidator(t *testing.T) {
	out := transformFileToString(t, "body", "TypedBodyController.ts", "assertPrune", "assert")
	mustContainAll(t, out, "@core.TypedBody({", `type: "assert"`)
}
