package test

import "testing"

// TestTransformBodyAssertCloneUsesAssertValidator verifies the @TypedBody
// generator routes `validate: "assertClone"` through the misc
// MiscAssertCloneProgrammer while recording `type: "assert"`.
//
// The clone family deep-copies the validated value through a generated cloner
// rather than returning the input by reference; assertClone is the throwing
// variant. It is generated by a distinct typia misc programmer from the plain
// assert path, so this pins that programmer selection.
//
//  1. Transform the body controller with validate "assertClone".
//  2. Read the emitted --out source.
//  3. Assert the validator metadata records the assert type.
//
// @evidence contracts/testing.md#behavioral-verification A native transform of the handwritten body fixture with mode assertClone must emit the assert discriminator. This detects absent argument injection and wrong family selection, rather than inspecting committed source arrangement.
// @evidence contracts/testing.md#independent-expectations The supported assertClone option selects the assert runtime protocol for body. The literal discriminator is derived from that option contract; this text assertion does not establish all helper internals or runtime semantics.
// @evidence contracts/testing.md#distinguishing-cases This owns assertClone's emitted family; sibling modes distinguish assert, is and validate selection. The option runtime batch owns body clone, equality, prune and malformed-value semantics, and actual HTTP feature cases own transport. Whole-output matching alone cannot distinguish two same-family decorators.
// @evidence contracts/testing.md#execution-ownership The core Go runner discovers this Test and invokes the native dispatcher in-process. The loaded fixture program and temporary emitted output exercise transformation without building or launching a native host; the generated-validator runtime batch owns installed-helper execution.
func TestTransformBodyAssertCloneUsesAssertValidator(t *testing.T) {
	out := transformFileToString(t, "body", "TypedBodyController.ts", "assertClone", "assert")
	mustContainAll(t, out, "@core.TypedBody({", `type: "assert"`)
}
