package test

import "testing"

// TestTransformBodyAssertCloneUsesAssertValidator verifies the @TypedBody
// generator routes `validate: "assertClone"` through typia plain
// PlainAssertCloneProgrammer while recording `type: "assert"`.
//
// The clone family deep-copies the validated value through a generated cloner
// rather than returning the input by reference; assertClone is the throwing
// variant. It is generated by a distinct typia plain programmer from the plain
// assert path, so this pins that programmer selection.
//
//  1. Transform the body controller with validate "assertClone".
//  2. Read the emitted --out source.
//  3. Assert the validator metadata records the assert type.
//
// @evidence contracts/testing.md#behavioral-verification A native transform of the handwritten body fixture with mode assertClone must emit the assert discriminator. This detects absent argument injection and wrong family selection, rather than inspecting committed source arrangement; and the body validator must also carry the marker of its own variant (__clone) while omitting the other variants' helpers.
// @evidence contracts/testing.md#independent-expectations The supported assertClone option selects the assert runtime protocol for body. The literal discriminator is derived from that option contract; this text assertion does not establish all helper internals or runtime semantics.
// @evidence contracts/testing.md#distinguishing-cases This owns assertClone's emitted family; sibling modes distinguish assert, is and validate selection. The shared E2E test_core_boundary_validation_http consumer owns compatible public helper clone, equality, prune and malformed-value semantics plus the actual manual body protocol; it does not claim ten global-configured installed programs executed. The assertion is scoped to every emitted call of the owning decorator, so another decorator of the same controller carrying the same discriminator cannot satisfy it.
// @evidence contracts/testing.md#execution-ownership The core Go runner discovers this Test and invokes the native dispatcher in-process. The loaded fixture program and temporary emitted output exercise transformation without building or launching a native host; the shared test_core_boundary_validation_http consumer owns compatible installed-helper execution.
func TestTransformBodyAssertCloneUsesAssertValidator(t *testing.T) {
	out := transformFileToString(t, "body", "TypedBodyController.ts", "assertClone", "assert")
	mustDecorateAll(t, out, `@core\.TypedBody`, "assert")
	mustSpansContain(t, out, `@core\.TypedBody`, "__clone")
	mustSpansOmit(t, out, `@core\.TypedBody`, "__prune")
}
