package test

import "testing"

// TestTransformBodyAssertCloneUsesAssertValidator verifies the @TypedBody
// generator routes `validate: "assertClone"` through the misc
// MiscAssertCloneProgrammer while recording `type: "assert"`.
//
// The clone family deep-copies the validated value through a generated cloner
// rather than returning the input by reference; assertClone is the throwing
// variant. It is generated by a distinct typia misc programmer from the plain
// assert path, so this pins that programmer selection.
//
//  1. Transform the body controller with validate "assertClone".
//  2. Read the emitted --out source.
//  3. Assert the validator metadata records the assert type.
func TestTransformBodyAssertCloneUsesAssertValidator(t *testing.T) {
	out := transformFileToString(t, "body", "TypedBodyController.ts", "assertClone", "assert")
	mustContainAll(t, out, "@core.TypedBody({", `type: "assert"`)
}
