/**
 * @module api.functional.bbs.articles
 * @packageDocumentation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IBbsArticle } from "../../../structures/IBbsArticle";

/**
 * @controller BbsArticleController.random
 * @path GET /bbs/articles/random
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function random(connection: IConnection): Promise<random.Output> {
  return PlainFetcher.fetch(connection, {
    ...random.METADATA,
    template: random.METADATA.path,
    path: random.path(),
  });
}
export namespace random {
  export type Output = IBbsArticle;

  export const METADATA = {
    method: "GET",
    path: "/bbs/articles/random",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/bbs/articles/random";
}
