import { IEncryptionPassword } from "./IEncryptionPassword";
import { IRandomGenerator } from "./IRandomGenerator";

/**
 * Connection information.
 *
 * `IConnection` is an interface ttype who represents connection information of the
 * remote HTTP server. You can target the remote HTTP server by wring the
 * {@link IConnection.host} variable down. Also, you can configure special header values
 * by specializing the {@link IConnection.headers} variable.
 *
 * If the remote HTTP server encrypts or decrypts its body data through the AES-128/256
 * algorithm, specify the {@link IConnection.encryption} with {@link IEncryptionPassword}
 * or {@link IEncryptionPassword.Closure} variable.
 *
 * @author Jenogho Nam - https://github.com/samchon
 */
export interface IConnection {
    /**
     * Host address of the remote HTTP server.
     */
    host: string;

    /**
     * Header values delivered to the remote HTTP server.
     */
    headers?: Record<string, string>;

    /**
     * Encryption password of its closure function.
     */
    encryption?: IEncryptionPassword | IEncryptionPassword.Closure;

    /**
     * Use simulation mode.
     *
     * If you configure this property to be `true` or assign an {@link IRandomGenerator}
     * instance, your SDK library does not send any request to remote backend server,
     * but just returns random data generated by `typia.random<T>()` function with
     * request data validation.
     *
     * By the way, to utilize this simulation mode, SDK library must be generated with
     * {@link INestiaConfig.simulate} option, too. Open `nestia.config.ts` file, and
     * configure {@link INestiaConfig.simulate} property to be `true`. Them, newly
     * generated SDK library would have a built-in mock-up data generator.
     *
     * @default false
     */
    simulate?: boolean | Partial<IRandomGenerator>;

    /**
     * A string indicating whether credentials will be sent with the request always, never, or only when sent to a same-origin URL. Sets request's credentials.
     */
    credentials?: RequestCredentials;
}