import { IConnection } from "./IConnection";
import { IFetchRoute } from "./IFetchRoute";
import { IPropagation } from "./IPropagation";
import { FetcherBase } from "./internal/FetcherBase";

/**
 * Utility class for `fetch` functions used in `@nestia/sdk`.
 *
 * `PlainFetcher` is a utility class designed for SDK functions generated by
 * [`@nestia/sdk`](https://nestia.io/docs/sdk/sdk), interacting with the remote
 * HTTP server API. In other words, this is a collection of dedicated `fetch()`
 * functions for `@nestia/sdk`.
 *
 * For reference, `PlainFetcher` class does not encrypt or decrypt the body data
 * at all. It just delivers plain data without any post processing. If you've
 * defined a controller method through `@EncryptedRoute` or `@EncryptedBody`
 * decorator, then {@link EncryptedFetcher} class would be used instead.
 *
 * @author Jeongho Nam - https://github.com/samchon
 * @evidence contracts/common.md#principled-implementation Bodies pass through unchanged, and a route that declares an encrypted body is refused before any request, because silently sending plain text for an encrypted route would break the security contract; everything else is `FetcherBase`.
 * @evidence contracts/common.md#clear-and-simple-design Two public operations that mirror `EncryptedFetcher`, with the encryption guard as their only own logic.
 * @evidence contracts/common.md#prohibited-implementation-shortcuts The refusal is the contract with the generated SDK, which chooses `EncryptedFetcher` for encrypted routes; no route or header is special-cased.
 * @evidence contracts/common.md#meaningful-documentation The namespace prose says when the generated SDK uses this fetcher and that it does no encryption.
 */
export namespace PlainFetcher {
  /**
   * Fetch function only for `HEAD` method.
   *
   * @param connection Connection information for the remote HTTP server
   * @param route Route information about the target API
   * @returns Nothing because of `HEAD` method
   * @evidence contracts/common.md#principled-implementation The overloads narrow the argument list by method; the implementation refuses an encrypted route and delegates to `FetcherBase.request`, which returns the body on success and throws `HttpError` otherwise.
   * @evidence contracts/common.md#clear-and-simple-design One guard and one delegation, with the overloads only splitting the types.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts The guard follows the route metadata, not a path or a connection.
   * @evidence contracts/common.md#meaningful-documentation Each overload documents its parameters and return value.
   */
  export function fetch(
    connection: IConnection,
    route: IFetchRoute<"HEAD">,
  ): Promise<void>;

  /**
   * Fetch function only for `GET` method.
   *
   * @param connection Connection information for the remote HTTP server
   * @param route Route information about the target API
   * @returns Response body data from the remote API
   */
  export function fetch<Output>(
    connection: IConnection,
    route: IFetchRoute<"GET">,
  ): Promise<Output>;

  /**
   * Fetch function for the `POST`, `PUT`, `PATCH` and `DELETE` methods.
   *
   * @param connection Connection information for the remote HTTP server
   * @param route Route information about the target API
   * @returns Response body data from the remote API
   */
  export function fetch<Input, Output>(
    connection: IConnection,
    route: IFetchRoute<"POST" | "PUT" | "PATCH" | "DELETE">,
    input?: Input,
    stringify?: (input: Input) => string,
  ): Promise<Output>;

  export async function fetch<Input, Output>(
    connection: IConnection,
    route: IFetchRoute<"DELETE" | "GET" | "HEAD" | "PATCH" | "POST" | "PUT">,
    input?: Input,
    stringify?: (input: Input) => string,
  ): Promise<Output> {
    if (route.request?.encrypted === true || route.response?.encrypted === true)
      throw new Error(
        "Error on PlainFetcher.fetch(): PlainFetcher doesn't have encryption ability. Use EncryptedFetcher instead.",
      );
    return FetcherBase.request({
      className: "PlainFetcher",
      encode: (input) => input,
      decode: (input) => input,
    })(connection, route, input, stringify);
  }

  /**
   * Fetch function that returns every response as an {@link IPropagation}.
   *
   * An HTTP failure status is returned as a failed branch instead of being
   * thrown. A route that declares an encrypted body and a transport failure
   * still throw.
   *
   * @evidence contracts/common.md#principled-implementation The implementation refuses an encrypted route and delegates to `FetcherBase.propagate`, which keeps the status, the headers, and the body of every response.
   * @evidence contracts/common.md#clear-and-simple-design One guard and one delegation, with the overloads only splitting the types.
   * @evidence contracts/common.md#prohibited-implementation-shortcuts The function adds no status-specific branch: the success flag comes from the status rules in `FetcherBase`.
   * @evidence contracts/common.md#meaningful-documentation The comment states what the returned union carries and which failures still throw.
   */
  export function propagate<Output extends IPropagation<any, any>>(
    connection: IConnection,
    route: IFetchRoute<"GET" | "HEAD">,
  ): Promise<Output>;

  export function propagate<Input, Output extends IPropagation<any, any>>(
    connection: IConnection,
    route: IFetchRoute<"DELETE" | "GET" | "HEAD" | "PATCH" | "POST" | "PUT">,
    input?: Input,
    stringify?: (input: Input) => string,
  ): Promise<Output>;

  export async function propagate<Input, Output extends IPropagation<any, any>>(
    connection: IConnection,
    route: IFetchRoute<"DELETE" | "GET" | "HEAD" | "PATCH" | "POST" | "PUT">,
    input?: Input,
    stringify?: (input: Input) => string,
  ): Promise<Output> {
    if (route.request?.encrypted === true || route.response?.encrypted === true)
      throw new Error(
        "Error on PlainFetcher.propagate(): PlainFetcher doesn't have encryption ability. Use EncryptedFetcher instead.",
      );
    return FetcherBase.propagate({
      className: "PlainFetcher",
      encode: (input) => input,
      decode: (input) => input,
    })(connection, route, input, stringify) as Promise<Output>;
  }
}
