/**
 * @packageDocumentation
 * @module api.functional.sellers.authenticate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { EncryptedFetcher } from "@nestia/fetcher/lib/EncryptedFetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Resolved } from "typia";

import type { ISeller } from "../../../structures/ISeller";

export * as password from "./password";

/**
 * Join as a seller.
 *
 * @param props.input Information of yours
 * @return Information of newly joined seller
 * @setHeader authorization.token Authorization
 *
 * @controller SellerAuthenticateController.join
 * @path POST /sellers/authenticate/join
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function join(
  connection: IConnection,
  props: join.IProps,
): Promise<join.Response> {
  const output: ISeller.IAuthorized = !!connection.simulate
    ? join.simulate(connection, props)
    : await EncryptedFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "text/plain",
          },
        },
        {
          ...join.METADATA,
          template: join.METADATA.path,
          path: join.path(),
        },
        props.input,
      );
  connection.headers ??= {};
  connection.headers.Authorization = output.authorization.token;
  return output;
}
export namespace join {
  export type IProps = {
    input: Body;
  };
  export type Body = ISeller.IJoin;
  export type Response = ISeller.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/sellers/authenticate/join",
    request: {
      type: "text/plain",
      encrypted: true,
    },
    response: {
      type: "text/plain",
      encrypted: true,
    },
    status: 201,
  } as const;

  export const path = () => "/sellers/authenticate/join";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<ISeller.IAuthorized> => typia.random<ISeller.IAuthorized>(g);
  export const simulate = (
    connection: IConnection,
    props: IProps,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "text/plain",
    });
    assert.body(() => typia.assert(props.input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Log-in as a seller.
 *
 * @param props.input Email and password
 * @return Information of the seller
 * @assignHeaders authorization
 *
 * @controller SellerAuthenticateController.login
 * @path POST /sellers/authenticate/login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  props: login.IProps,
): Promise<login.Response> {
  const output: ISeller.IAuthorized = !!connection.simulate
    ? login.simulate(connection, props)
    : await EncryptedFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "text/plain",
          },
        },
        {
          ...login.METADATA,
          template: login.METADATA.path,
          path: login.path(),
        },
        props.input,
      );
  connection.headers ??= {};
  Object.assign(connection.headers, output.authorization);
  return output;
}
export namespace login {
  export type IProps = {
    input: Body;
  };
  export type Body = ISeller.ILogin;
  export type Response = ISeller.IAuthorized;

  export const METADATA = {
    method: "POST",
    path: "/sellers/authenticate/login",
    request: {
      type: "text/plain",
      encrypted: true,
    },
    response: {
      type: "text/plain",
      encrypted: true,
    },
    status: 201,
  } as const;

  export const path = () => "/sellers/authenticate/login";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<ISeller.IAuthorized> => typia.random<ISeller.IAuthorized>(g);
  export const simulate = (
    connection: IConnection,
    props: IProps,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "text/plain",
    });
    assert.body(() => typia.assert(props.input));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * Erase the seller by itself.
 * @controller SellerAuthenticateController.exit
 * @path DELETE /sellers/authenticate/exit
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function exit(connection: IConnection): Promise<void> {
  return !!connection.simulate
    ? exit.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...exit.METADATA,
        template: exit.METADATA.path,
        path: exit.path(),
      });
}
export namespace exit {
  export const METADATA = {
    method: "DELETE",
    path: "/sellers/authenticate/exit",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/sellers/authenticate/exit";
  export const random = (g?: Partial<typia.IRandomGenerator>): Resolved<void> =>
    typia.random<void>(g);
  export const simulate = (connection: IConnection): void => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
