/**
 * @packageDocumentation
 * @module api.functional.arraySimple
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, IPropagation, HttpError } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Resolved } from "typia";
import type { Format } from "typia/lib/tags/Format";

import type { IPerson } from "../../structures/IPerson";

/**
 * @controller ArraySimpleController.index
 * @path GET /arraySimple
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(connection: IConnection): Promise<index.Output> {
  return !!connection.simulate
    ? index.simulate(connection)
    : PlainFetcher.propagate<any>(connection, {
        ...index.METADATA,
        template: index.METADATA.path,
        path: index.path(),
      });
}
export namespace index {
  export type Output = IPropagation<
    {
      200: IPerson[];
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/arraySimple",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/arraySimple";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IPerson[]> => typia.random<IPerson[]>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}

/**
 * @controller ArraySimpleController.at
 * @path GET /arraySimple/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection, props)
    : PlainFetcher.propagate<any>(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(props),
      });
}
export namespace at {
  export type Props = {
    id: string & Format<"uuid">;
  };
  export type Output = IPropagation<
    {
      200: IPerson;
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/arraySimple/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (p: { id: string & Format<"uuid"> }) =>
    `/arraySimple/${encodeURIComponent(p.id?.toString() ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IPerson> => typia.random<IPerson>(g);
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    try {
      assert.param("id")(() => typia.assert(props.id));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}

/**
 * @controller ArraySimpleController.store
 * @path POST /arraySimple
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function store(
  connection: IConnection,
  props: store.Props,
): Promise<store.Output> {
  return !!connection.simulate
    ? store.simulate(connection, props)
    : PlainFetcher.propagate<any, any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...store.METADATA,
          template: store.METADATA.path,
          path: store.path(),
        },
        props.body,
      );
}
export namespace store {
  export type Props = {
    body: Body;
  };
  export type Body = IPerson;
  export type Output = IPropagation<
    {
      201: IPerson;
    },
    201
  >;

  export const METADATA = {
    method: "POST",
    path: "/arraySimple",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/arraySimple";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<IPerson> => typia.random<IPerson>(g);
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return {
      success: true,
      status: 201,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}
