import { TestValidator } from "@nestia/e2e";

import api from "../../api";

/**
 * Verifies a `HEAD` route resolves through the SDK with no content.
 *
 * 1. Call the `HEAD` route through the SDK.
 * 2. Assert the result is `undefined`, since a `HEAD` response has no body.
 *
 * @evidence contracts/testing.md#behavioral-verification The generated method.head request must resolve with exactly undefined.
 * @evidence contracts/testing.md#independent-expectations The authored HEAD handler is bodyless and HTTP HEAD carries no response body; that independent contract establishes undefined rather than an emitted-output snapshot.
 * @evidence contracts/testing.md#distinguishing-cases HEAD contrasts ordinary GET response decoding and rejects an unexpected decoded payload. This single route does not assert every header/status or HEAD error response.
 * @evidence contracts/testing.md#execution-ownership The matching exported case is discovered and awaited by its actual feature entry after generation and consumer compilation. Type controls fail compilation and runtime assertions reject the report; empty discovery rejects the entry.
 * @evidence contracts/e2e.md#necessary-boundary Actual generated HEAD dispatch and fetcher bodyless response handling must connect over HTTP; a void type identity does not establish it.
 * @evidence contracts/e2e.md#shared-execution The request reuses the common packed installation, single producer and generated consumer programs, and one backend; it introduces no independent compilation or server.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Explicit scenario route/type namespaces prevent cross-scenario dispatch; authored request values remain local and the common entry closes the application after all cases settle.
 * @evidence contracts/e2e.md#preserved-coverage The original authored request and exact echo/type/status assertions remain in this case. Generated automated duplicates are regenerated by the common E2eGenerator rather than copied as authored cases.
 */
export const test_method_api_method_head = async (
  connection: api.IConnection,
): Promise<void> => {
  TestValidator.equals(
    "output",
    await api.functional.method.method.head(connection),
    undefined,
  );
};
