cp ../README.md ../packages/agent/README.md
cp ../README.md ../packages/benchmark/README.md
cp ../README.md ../packages/chat/README.md
cp ../README.md ../packages/cli/README.md
cp ../README.md ../packages/core/README.md
cp ../README.md ../packages/e2e/README.md
cp ../README.md ../packages/fetcher/README.md
cp ../README.md ../packages/migrate/README.md
cp ../README.md ../packages/sdk/README.md
