/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IToken } from "../structures/IToken";

/**
 * @controller SecurityController.oauth2
 * @path GET /oauth2
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function oauth2(
    connection: IConnection,
): Promise<oauth2.Output> {
    return PlainFetcher.fetch(
        connection,
        {
            ...oauth2.METADATA,
            path: oauth2.path(),
        } as const,
    );
}
export namespace oauth2 {
    export type Output = Primitive<IToken>;

    export const METADATA = {
        method: "GET",
        path: "/oauth2",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/oauth2`;
    }
}