/**
 * @packageDocumentation
 * @module api.functional.status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection, Primitive } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

import type { IBbsArticle } from "../../structures/IBbsArticle";

/**
 * @controller StatusController.random
 * @path GET /status/random
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function random(
    connection: IConnection,
): Promise<random.Output> {
    return PlainFetcher.fetch(
        connection,
        {
            ...random.METADATA,
            path: random.path(),
        } as const,
    );
}
export namespace random {
    export type Output = Primitive<IBbsArticle>;

    export const METADATA = {
        method: "GET",
        path: "/status/random",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: 300,
    } as const;

    export const path = (): string => {
        return `/status/random`;
    }
}