/**
 * @packageDocumentation
 * @module api.functional.partial_dto_test
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  IPropagation,
  Primitive,
  Resolved,
} from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IOriginal } from "../../structures/IOriginal";

export * as partial_interface from "./partial_interface";
export * as partial_type from "./partial_type";

/**
 * @controller PartialDTOTestController.original
 * @path GET /partial-dto-test/original
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function original(connection: IConnection): Promise<
  IPropagation<
    {
      200: IOriginal;
    },
    200
  >
> {
  return !!connection.simulate
    ? original.simulate(connection)
    : PlainFetcher.propagate<any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...original.METADATA,
          template: original.METADATA.path,
          path: original.path(),
        },
      );
}
export namespace original {
  export type Output = IPropagation<
    {
      200: IOriginal;
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/partial-dto-test/original",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/partial-dto-test/original";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<IOriginal>> => typia.random<Primitive<IOriginal>>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}
