/**
 * @packageDocumentation
 * @module api.functional.performance
 */
//================================================================
import { Fetcher, Primitive } from "nestia-fetcher";
import type { IConnection } from "nestia-fetcher";

import type { IPerformance } from "./../../structures/performance/IMemoryUsage";

/**
 * Get performance information of the server.
 * 
 * @return Performance information
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller PerformanceController.get()
 * @path GET /performance
 */
export function get
    (
        connection: IConnection
    ): Promise<get.Output>
{
    return Fetcher.fetch
    (
        connection,
        get.ENCRYPTED,
        get.METHOD,
        get.path()
    );
}
export namespace get
{
    export type Output = Primitive<IPerformance>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/performance";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: true,
    };

    export function path(): string
    {
        return `/performance`;
    }
}