/**
 * @module api.functional.x.bbs
 * @packageDocumentation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as articles from "./articles";
