/**
 * @packageDocumentation
 * @module api.functional.tupleHierarchicalController
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";
import type { Resolved } from "typia";

/**
 * @controller TupleHierarchicalController.index
 * @path GET /tupleHierarchicalController
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(connection: IConnection): Promise<index.Output> {
  return !!connection.simulate
    ? index.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...index.METADATA,
        template: index.METADATA.path,
        path: index.path(),
      });
}
export namespace index {
  export type Output = [
    boolean,
    null,
    number,
    [boolean, null, [number, [boolean, string]]],
    [number, [string, boolean, [number, number, [boolean, string]][]][]],
  ][];

  export const METADATA = {
    method: "GET",
    path: "/tupleHierarchicalController",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/tupleHierarchicalController";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<
    [
      boolean,
      null,
      number,
      [boolean, null, [number, [boolean, string]]],
      [number, [string, boolean, [number, number, [boolean, string]][]][]],
    ][]
  > =>
    typia.random<
      [
        boolean,
        null,
        number,
        [boolean, null, [number, [boolean, string]]],
        [number, [string, boolean, [number, number, [boolean, string]][]][]],
      ][]
    >(g);
  export const simulate = (connection: IConnection): Output => {
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * @controller TupleHierarchicalController.at
 * @path GET /tupleHierarchicalController/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Output> {
  return !!connection.simulate
    ? at.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...at.METADATA,
        template: at.METADATA.path,
        path: at.path(props),
      });
}
export namespace at {
  export type Props = {
    id: number;
  };
  export type Output = [
    boolean,
    null,
    number,
    [boolean, null, [number, [boolean, string]]],
    [number, [string, boolean, [number, number, [boolean, string]][]][]],
  ];

  export const METADATA = {
    method: "GET",
    path: "/tupleHierarchicalController/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (p: { id: number }) =>
    `/tupleHierarchicalController/${encodeURIComponent(p.id?.toString() ?? "null")}`;
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<
    [
      boolean,
      null,
      number,
      [boolean, null, [number, [boolean, string]]],
      [number, [string, boolean, [number, number, [boolean, string]][]][]],
    ]
  > =>
    typia.random<
      [
        boolean,
        null,
        number,
        [boolean, null, [number, [boolean, string]]],
        [number, [string, boolean, [number, number, [boolean, string]][]][]],
      ]
    >(g);
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("id")(() => typia.assert(props.id));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}

/**
 * @controller TupleHierarchicalController.store
 * @path POST /tupleHierarchicalController
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function store(
  connection: IConnection,
  props: store.Props,
): Promise<store.Output> {
  return !!connection.simulate
    ? store.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...store.METADATA,
          template: store.METADATA.path,
          path: store.path(),
        },
        props.body,
      );
}
export namespace store {
  export type Props = {
    body: Body;
  };
  export type Body = [
    boolean,
    null,
    number,
    [boolean, null, [number, [boolean, string]]],
    [number, [string, boolean, [number, number, [boolean, string]][]][]],
  ];
  export type Output = [
    boolean,
    null,
    number,
    [boolean, null, [number, [boolean, string]]],
    [number, [string, boolean, [number, number, [boolean, string]][]][]],
  ];

  export const METADATA = {
    method: "POST",
    path: "/tupleHierarchicalController",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/tupleHierarchicalController";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<
    [
      boolean,
      null,
      number,
      [boolean, null, [number, [boolean, string]]],
      [number, [string, boolean, [number, number, [boolean, string]][]][]],
    ]
  > =>
    typia.random<
      [
        boolean,
        null,
        number,
        [boolean, null, [number, [boolean, string]]],
        [number, [string, boolean, [number, number, [boolean, string]][]][]],
      ]
    >(g);
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props.body));
    return random(
      "object" === typeof connection.simulate && null !== connection.simulate
        ? connection.simulate
        : undefined,
    );
  };
}
