/**
 * @packageDocumentation
 * @module api.functional._delete
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller DeleteController.erase
 * @path DELETE /delete/erase
 * @accessor api.functional._delete.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(connection: IConnection): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/delete/erase",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/delete/erase";
}
