import { TestValidator } from "@nestia/e2e";
import fs from "fs";

export async function test_swagger(): Promise<void> {
  const { NESTIA_CONFIG } = await import(
    __dirname + "/../../../../nestia.config.ts"
  );
  const pack = JSON.parse(
    await fs.promises.readFile(__dirname + "/../../../../package.json", "utf8"),
  );
  const swagger = JSON.parse(
    await fs.promises.readFile(__dirname + "/../../../../swagger.json", "utf8"),
  );

  TestValidator.equals("info.version", pack.version, swagger.info.version);
  TestValidator.equals(
    "info.title",
    NESTIA_CONFIG.swagger.info.title,
    swagger.info.title,
  );
  TestValidator.equals(
    "info.description",
    swagger.info.description,
    "Generated by nestia - https://github.com/samchon/nestia",
  );
  TestValidator.equals(
    "servers",
    NESTIA_CONFIG.swagger.servers,
    swagger.servers,
  );
}
