/**
 * @packageDocumentation
 * @module api.functional.performance
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  IPropagation,
  Primitive,
  Resolved,
} from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { process } from "../../structures/process";

/**
 * @controller PerformanceController.cpu
 * @path GET /performance/cpu
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cpu(connection: IConnection): Promise<
  IPropagation<
    {
      200: process.global.NodeJS.CpuUsage;
    },
    200
  >
> {
  return !!connection.simulate
    ? cpu.simulate(connection)
    : PlainFetcher.propagate<any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...cpu.METADATA,
          template: cpu.METADATA.path,
          path: cpu.path(),
        },
      );
}
export namespace cpu {
  export type Output = IPropagation<
    {
      200: process.global.NodeJS.CpuUsage;
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/performance/cpu",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/performance/cpu";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<process.global.NodeJS.CpuUsage>> =>
    typia.random<Primitive<process.global.NodeJS.CpuUsage>>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}

/**
 * @controller PerformanceController.memory
 * @path GET /performance/memory
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function memory(connection: IConnection): Promise<
  IPropagation<
    {
      200: process.global.NodeJS.MemoryUsage;
    },
    200
  >
> {
  return !!connection.simulate
    ? memory.simulate(connection)
    : PlainFetcher.propagate<any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...memory.METADATA,
          template: memory.METADATA.path,
          path: memory.path(),
        },
      );
}
export namespace memory {
  export type Output = IPropagation<
    {
      200: process.global.NodeJS.MemoryUsage;
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/performance/memory",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/performance/memory";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<process.global.NodeJS.MemoryUsage>> =>
    typia.random<Primitive<process.global.NodeJS.MemoryUsage>>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}

/**
 * @controller PerformanceController.resource
 * @path GET /performance/resource
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function resource(connection: IConnection): Promise<
  IPropagation<
    {
      200: process.global.NodeJS.ResourceUsage;
    },
    200
  >
> {
  return !!connection.simulate
    ? resource.simulate(connection)
    : PlainFetcher.propagate<any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...resource.METADATA,
          template: resource.METADATA.path,
          path: resource.path(),
        },
      );
}
export namespace resource {
  export type Output = IPropagation<
    {
      200: process.global.NodeJS.ResourceUsage;
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/performance/resource",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/performance/resource";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<process.global.NodeJS.ResourceUsage>> =>
    typia.random<Primitive<process.global.NodeJS.ResourceUsage>>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}
