/**
 * @packageDocumentation
 * @module api.functional.tupleRestController
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  IConnection,
  IPropagation,
  Primitive,
  Resolved,
} from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

/**
 * @controller TupleRestController.get
 * @path GET /tupleRestController
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function get(connection: IConnection): Promise<
  IPropagation<
    {
      200: [boolean, number, ...string[]];
    },
    200
  >
> {
  return !!connection.simulate
    ? get.simulate(connection)
    : PlainFetcher.propagate<any>(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...get.METADATA,
          template: get.METADATA.path,
          path: get.path(),
        },
      );
}
export namespace get {
  export type Output = IPropagation<
    {
      200: [boolean, number, ...string[]];
    },
    200
  >;

  export const METADATA = {
    method: "GET",
    path: "/tupleRestController",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/tupleRestController";
  export const random = (
    g?: Partial<typia.IRandomGenerator>,
  ): Resolved<Primitive<[boolean, number, ...string[]]>> =>
    typia.random<Primitive<[boolean, number, ...string[]]>>(g);
  export const simulate = (connection: IConnection): Output => {
    return {
      success: true,
      status: 200,
      headers: {
        "Content-Type": "application/json",
      },
      data: random(
        "object" === typeof connection.simulate && null !== connection.simulate
          ? connection.simulate
          : undefined,
      ),
    } as Output;
  };
}
