/**
 * @packageDocumentation
 * @module api.functional.api.v2.common
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
export * as health from "./health";