import { DynamicExecutor, TestValidator } from "@nestia/e2e";
import fs from "node:fs";
import path from "node:path";
import typia from "typia";

import api from "../api";
import { IRichContext } from "../internal/IRichContext";
import { IBbsArticle } from "../oracle/simulation_original/structures/IBbsArticle";

/**
 * Verifies the original simulator population never calls the live backend.
 *
 * A generated client can accidentally use its normal fetch branch while still
 * returning a valid DTO. Live producer observations distinguish that error; the
 * real positive proves that both observers can detect an actual request.
 *
 * 1. Call the real Bbs endpoint and prove its request counter and Global bit
 *    change.
 * 2. Reset the bit, execute all seven original cases and every fresh generated
 *    HTTP case with simulate true, and compare exact execution identities.
 * 3. Assert no native request or Bbs handler ran, then validate a healthy
 *    simulator recovery through the independent original DTO.
 *
 * @evidence contracts/testing.md#behavioral-verification The actual generated simulator runs all seven original cases, including five distinct HTTP 400 controls, and every generated HTTP case; an active native server counter and actual producer Bbs Global bit must remain unchanged/false throughout simulation.
 * @evidence contracts/testing.md#independent-expectations The original authored IBbsArticle DTO, literal valid UUID, original invalid values and pre-generation-independent file/export identity census own the expected results. The preceding real request must increment the observer and set the same producer bit.
 * @evidence contracts/testing.md#distinguishing-cases Real positive, numeric body title, invalid date, query page string, null nonnullable section and invalid UUID are separate verdicts. Health void, authored performance DTO, full generated HTTP population and healthy recovery remain executable.
 * @evidence contracts/testing.md#execution-ownership The common consumer calls this matching export before ordinary HTTP, WebSocket or lazy MCP acquisition for each adapter; its two DynamicExecutor reports require every input identity exactly once and retain all case failures.
 * @evidence contracts/e2e.md#necessary-boundary Generated simulation helpers, the compiled consumer, and actual producer/server observations must connect; DTO shape success alone cannot prove the network branch was unused.
 * @evidence contracts/e2e.md#shared-execution Both adapter lifetimes reuse the one existing installation, producer, generator outputs and compiled consumer. This case creates no compiler, generator, application, process or client session.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Simulation runs serially before ordinary traffic and MCP acquisition. Only the owned producer bit resets after its active positive; the passive native event counter is never reset during the observed interval. Each simulation specimen receives its own connection/header object.
 * @evidence contracts/e2e.md#preserved-coverage Original six Bbs handlers, DTO tags, nullable sections, seven authored cases and the full generated HTTP population retain named executable destinations. WS/MCP are not generated by E2eGenerator's public HTTP protocol branch and retain their separate actual runtime owners; no generated HTTP case is filtered by type or name.
 */
export const test_simulation_original_population = async (
  connection: api.IConnection,
  context: IRichContext,
): Promise<void> => {
  const id = "7a1c7b36-0f6e-4c55-9b1e-1f2d3c4b5a69";
  const beforeReal = context.httpRequests();
  const real = await api.functional.simulation_original.bbs.articles.at(
    { ...connection, simulate: false },
    "general",
    id,
  );
  typia.assert<IBbsArticle>(real);
  TestValidator.equals("real Bbs UUID", id, real.id);
  TestValidator.predicate(
    "native observer detects real traffic",
    context.httpRequests() > beforeReal,
  );
  TestValidator.equals(
    "producer Global detects real handler",
    true,
    context.simulationOriginal.used(),
  );
  context.simulationOriginal.reset();
  const beforeSimulation = context.httpRequests();

  const failures: unknown[] = [];
  for (const [label, location, required] of [
    ["original", path.join(__dirname, "features"), 7],
    ["fresh HTTP", path.join(__dirname, "../features/generated"), undefined],
  ] as const) {
    const expected: string[] = [];
    const inventory = (directory: string): void => {
      for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
        const file = path.join(directory, entry.name);
        if (entry.isDirectory()) inventory(file);
        else if (entry.name.startsWith("test_") && entry.name.endsWith(".js"))
          expected.push(
            `${path.relative(location, file).split(path.sep).join("/")}#${entry.name.slice(0, -3)}`,
          );
      }
    };
    inventory(location);
    if (required !== undefined)
      TestValidator.equals<number>(
        `${label} original case census`,
        required,
        expected.length,
      );
    TestValidator.predicate(
      `${label} nonempty population`,
      expected.length > 0,
    );
    const report = await DynamicExecutor.validate({
      location,
      extension: "js",
      prefix: "test",
      simultaneous: 1,
      parameters: () => [
        { ...connection, headers: { ...connection.headers }, simulate: true },
      ],
      onComplete: (execution) => {
        console.log(
          ` - [simulation ${label}] ${path.relative(location, execution.location)}#${execution.name}: ${execution.error === null ? "passed" : "failed"}`,
        );
        if (execution.error !== null) console.error(execution.error);
      },
    });
    const identities = new Map<string, number>();
    for (const execution of report.executions) {
      const identity = `${path.relative(location, execution.location).split(path.sep).join("/")}#${execution.name}`;
      identities.set(identity, (identities.get(identity) ?? 0) + 1);
      if (execution.error !== null) failures.push(execution.error);
    }
    TestValidator.equals(
      `${label} execution count`,
      expected.length,
      report.executions.length,
    );
    for (const identity of expected)
      TestValidator.equals(
        `${label} ${identity} exactly once`,
        1,
        identities.get(identity),
      );
    console.log(
      `Simulation census [${label}]: ${expected.length} expected, ${report.executions.length} executed; HTTP protocol only, generated WS/MCP population 0.`,
    );
  }
  TestValidator.equals(
    "simulation native traffic unchanged",
    beforeSimulation,
    context.httpRequests(),
  );
  TestValidator.equals(
    "original Bbs Global remains unused",
    false,
    context.simulationOriginal.used(),
  );
  const recovered = await api.functional.simulation_original.bbs.articles.at(
    { ...connection, simulate: true },
    "general",
    id,
  );
  typia.assert<IBbsArticle>(recovered);
  TestValidator.equals(
    "healthy simulator recovery sends no request",
    beforeSimulation,
    context.httpRequests(),
  );
  TestValidator.equals(
    "healthy simulator recovery leaves Global unused",
    false,
    context.simulationOriginal.used(),
  );
  if (failures.length)
    throw new AggregateError(
      failures,
      "Original/full HTTP simulator population failed.",
    );
};
