/**
 * @packageDocumentation
 * @module api.functional.sellers.sales.comments
 */
//================================================================
import { AesPkcs5 } from "./../../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../../__internal/Fetcher";
import { Primitive } from "./../../../../Primitive";
import type { IConnection } from "./../../../../IConnection";

import type { IPage } from "./../../../../structures/common/IPage";
import type { ISaleComment } from "./../../../../structures/sales/articles/ISaleComment";


/**
 * Get page of comments.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleCommentsController.index()
 * @path GET /sellers/:section/sales/:saleId/comments/:articleId/
 */
export function index(connection: IConnection, section: string, saleId: number, articleId: number, input: Primitive<index.Query>): Promise<index.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":true},
        "GET",
        `/sellers/${section}/sales/${saleId}/comments/${articleId}/?${new URLSearchParams(input as any).toString()}`
    );
}
export namespace index
{
    export type Query = Primitive<IPage.IRequest<string>>;
    export type Output = Primitive<IPage<ISaleComment>>;
}

/**
 * Store a new comment.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleCommentsController.store()
 * @path POST /sellers/:section/sales/:saleId/comments/:articleId/
 */
export function store(connection: IConnection, section: string, saleId: number, articleId: number, input: Primitive<store.Input>): Promise<store.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "POST",
        `/sellers/${section}/sales/${saleId}/comments/${articleId}/`,
        input
    );
}
export namespace store
{
    export type Input = Primitive<ISaleComment.IStore>;
    export type Output = Primitive<ISaleComment>;
}

/**
 * Remove a comment.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleCommentsController.remove()
 * @path DELETE /sellers/:section/sales/:saleId/comments/:articleId/:commentId
 */
export function remove(connection: IConnection, section: string, saleId: number, articleId: number, commentId: number): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":false},
        "DELETE",
        `/sellers/${section}/sales/${saleId}/comments/${articleId}/${commentId}`
    );
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
