/**
 * @packageDocumentation
 * @module api.functional.sellers.sales.questions
 */
//================================================================
import { AesPkcs5 } from "./../../../../__internal/AesPkcs5";
import { Fetcher } from "./../../../../__internal/Fetcher";
import { Primitive } from "./../../../../Primitive";
import type { IConnection } from "./../../../../IConnection";

import type { ISaleArticle } from "./../../../../structures/sales/articles/ISaleArticle";
import type { ISaleInquiry } from "./../../../../structures/sales/articles/ISaleInquiry";
import type { IPage } from "./../../../../structures/common/IPage";


/**
 * Store a new answer.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleQuestionsController.store()
 * @path POST /sellers/:section/sales/:saleId/questions/:inquiryId
 */
export function store(connection: IConnection, section: string, saleId: number, inquiryId: number, input: Primitive<store.Input>): Promise<store.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "POST",
        `/sellers/${section}/sales/${saleId}/questions/${inquiryId}`,
        input
    );
}
export namespace store
{
    export type Input = Primitive<ISaleArticle.IContent>;
    export type Output = Primitive<ISaleInquiry<ISaleArticle.IContent>>;
}

/**
 * Update an answer.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleQuestionsController.update()
 * @path POST /sellers/:section/sales/:saleId/questions/:inquiryId
 */
export function update(connection: IConnection, section: string, saleId: number, inquiryId: number, input: Primitive<update.Input>): Promise<update.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":true,"output_encrypted":true},
        "POST",
        `/sellers/${section}/sales/${saleId}/questions/${inquiryId}`,
        input
    );
}
export namespace update
{
    export type Input = Primitive<ISaleArticle.IContent>;
    export type Output = Primitive<ISaleInquiry<ISaleArticle.IContent>>;
}

/**
 * Remove an answer.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleQuestionsController.remove()
 * @path DELETE /sellers/:section/sales/:saleId/questions/:inquiryId
 */
export function remove(connection: IConnection, section: string, saleId: number, inquiryId: number): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":false},
        "DELETE",
        `/sellers/${section}/sales/${saleId}/questions/${inquiryId}`
    );
}

/**
 * Get page of summarized inquiries.
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleQuestionsController.index()
 * @path GET /sellers/:section/sales/:saleId/questions/
 */
export function index(connection: IConnection, section: string, saleId: number, input: Primitive<index.Query>): Promise<index.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":true},
        "GET",
        `/sellers/${section}/sales/${saleId}/questions/?${new URLSearchParams(input as any).toString()}`
    );
}
export namespace index
{
    export type Query = Primitive<ISaleInquiry.IRequest>;
    export type Output = Primitive<IPage<ISaleInquiry.ISummary>>;
}

/**
 * Get detailed record of an inquiry
 * 
 * @param [object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @param [object Object],[object Object],[object Object]
 * @return [object Object]
 * @throw [object Object]
 * @throw [object Object]
 * 
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 * @controller SellerSaleQuestionsController.at()
 * @path GET /sellers/:section/sales/:saleId/questions/:id
 */
export function at(connection: IConnection, section: string, saleId: number, id: number): Promise<at.Output>
{
    return Fetcher.fetch
    (
        connection,
        {"input_encrypted":false,"output_encrypted":true},
        "GET",
        `/sellers/${section}/sales/${saleId}/questions/${id}`
    );
}
export namespace at
{
    export type Output = Primitive<ISaleInquiry<ISaleArticle.IContent>>;
}



//---------------------------------------------------------
// TO PREVENT THE UNUSED VARIABLE ERROR
//---------------------------------------------------------
AesPkcs5;
Fetcher;
Primitive;
