/**
 * @packageDocumentation
 * @module api.functional.consumers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as systematic from "./systematic";
