import { RandomGenerator, TestValidator } from "@nestia/e2e";

import api from "../../api";

/**
 * Verifies api plain string through its generated consumer.
 *
 * The authored input and handler establish the observable contract.
 *
 * 1. Exercise the retained generated request or document.
 * 2. Assert its exact payload, shape or selected media constraints.
 *
 * @evidence contracts/testing.md#behavioral-verification Generated plain.string must return the exact submitted one-million-character string.
 * @evidence contracts/testing.md#independent-expectations The original generated alphabet string itself is the independent expected echo; no server-generated expected snapshot or random-response shape oracle supplies equality.
 * @evidence contracts/testing.md#distinguishing-cases A large text payload contrasts constant/template/ordinary parser cases. One accepted size does not certify a maximum limit or malformed request.
 * @evidence contracts/testing.md#execution-ownership The matching exported case is discovered and awaited by its actual feature entry after generation and consumer compilation. Type controls fail compilation and runtime assertions reject the report; empty discovery rejects the entry.
 * @evidence contracts/e2e.md#necessary-boundary Actual plain HTTP body reading and generated text response decoding must preserve the full large payload; a direct string equality or stream unit cannot establish transport.
 * @evidence contracts/e2e.md#shared-execution The request reuses the common packed installation, single producer and generated consumer programs, and one backend; it introduces no independent compilation or server.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Explicit scenario route/type namespaces prevent cross-scenario dispatch; authored request values remain local and the common entry closes the application after all cases settle.
 * @evidence contracts/e2e.md#preserved-coverage The original authored request and exact echo/type/status assertions remain in this case. Generated automated duplicates are regenerated by the common E2eGenerator rather than copied as authored cases.
 */
export const test_plain_api_plain_string = async (
  connection: api.IConnection,
): Promise<void> => {
  const x: string = RandomGenerator.alphabets(1_000_000);
  const y: string = await api.functional.plain.plain.string(connection, x);
  TestValidator.equals("string", x, y);
};
