import { TestValidator } from "@nestia/e2e";

import api from "../../api";

/**
 * Verifies api plain constant through its generated consumer.
 *
 * The authored input and handler establish the observable contract.
 *
 * 1. Exercise the retained generated request or document.
 * 2. Assert its exact payload, shape or selected media constraints.
 *
 * @evidence contracts/testing.md#behavioral-verification Generated plain.constant must echo each exact A/B/C value.
 * @evidence contracts/testing.md#independent-expectations The authored constant union and echo handler establish all three accepted literal expectations independently of response output.
 * @evidence contracts/testing.md#distinguishing-cases All members of the finite literal union run rather than a single successful value. This case does not submit a value outside that union; dedicated plain diagnostic owners retain invalid declaration checks.
 * @evidence contracts/testing.md#execution-ownership The matching exported case is discovered and awaited by its actual feature entry after generation and consumer compilation. Type controls fail compilation and runtime assertions reject the report; empty discovery rejects the entry.
 * @evidence contracts/e2e.md#necessary-boundary Actual generated text encoding, PlainBody validation and route response handling must connect; a local union validator cannot certify text transport.
 * @evidence contracts/e2e.md#shared-execution The request reuses the common packed installation, single producer and generated consumer programs, and one backend; it introduces no independent compilation or server.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Explicit scenario route/type namespaces prevent cross-scenario dispatch; authored request values remain local and the common entry closes the application after all cases settle.
 * @evidence contracts/e2e.md#preserved-coverage The original authored request and exact echo/type/status assertions remain in this case. Generated automated duplicates are regenerated by the common E2eGenerator rather than copied as authored cases.
 */
export const test_plain_api_plain_constant = async (
  connection: api.IConnection,
): Promise<void> => {
  for (const x of ["A", "B", "C"] as const) {
    const y = await api.functional.plain.plain.constant(connection, x);
    TestValidator.equals("constant", x, y as "A");
  }
};
