import { TestValidator } from "@nestia/e2e";

import api from "../../api";

/**
 * Verifies api plain template through its generated consumer.
 *
 * The authored input and handler establish the observable contract.
 *
 * 1. Exercise the retained generated request or document.
 * 2. Assert its exact payload, shape or selected media constraints.
 *
 * @evidence contracts/testing.md#behavioral-verification Generated plain.template must echo the exact something_123_interesting_abc_is_not_true_it? string.
 * @evidence contracts/testing.md#independent-expectations The authored template-literal body declaration accepts the explicit chosen string and its echo handler establishes unchanged output independently of generated serializers.
 * @evidence contracts/testing.md#distinguishing-cases A string containing numeric/word/boolean template parts and punctuation contrasts the finite constant and unrestricted long-string cases. This is one accepted template value, not exhaustive invalid-template coverage.
 * @evidence contracts/testing.md#execution-ownership The matching exported case is discovered and awaited by its actual feature entry after generation and consumer compilation. Type controls fail compilation and runtime assertions reject the report; empty discovery rejects the entry.
 * @evidence contracts/e2e.md#necessary-boundary Actual native template validation and generated plain-text HTTP client must connect; a compile-time template assignment cannot certify the body reader.
 * @evidence contracts/e2e.md#shared-execution The request reuses the common packed installation, single producer and generated consumer programs, and one backend; it introduces no independent compilation or server.
 * @evidence contracts/e2e.md#state-isolation-and-reuse-validity Explicit scenario route/type namespaces prevent cross-scenario dispatch; authored request values remain local and the common entry closes the application after all cases settle.
 * @evidence contracts/e2e.md#preserved-coverage The original authored request and exact echo/type/status assertions remain in this case. Generated automated duplicates are regenerated by the common E2eGenerator rather than copied as authored cases.
 */
export const test_plain_api_plain_template = async (
  connection: api.IConnection,
): Promise<void> => {
  const x = "something_123_interesting_abc_is_not_true_it?";
  const y: string = await api.functional.plain.plain.template(connection, x);

  TestValidator.equals("template", x as string, y);
};
