import { IRequestBodyValidator } from "../options/IRequestBodyValidator";
import { IMcpRouteReflect } from "./internal/IMcpRouteReflect";
import { validate_request_body } from "./internal/validate_request_body";

/**
 * MCP (Model Context Protocol) route decorator.
 *
 * `@McpRoute()` marks a controller method as a callable MCP tool. When the
 * application bootstraps, every method annotated with this decorator is
 * registered on the MCP server built by {@link McpAdaptor.upgrade}, making it
 * reachable by LLM clients (Claude Desktop, Cursor, OpenAI function calling,
 * etc.) through the standard Streamable HTTP transport.
 *
 * For type-safe tool inputs, decorate exactly one parameter of the method
 * with {@link McpRoute.Params}. The parameter type `T` is analyzed at compile
 * time by the nestia transformer, which generates both a runtime validator
 * (powered by typia) and the JSON Schema attached to `inputSchema` in
 * `tools/list` responses. Manually supplying `inputSchema` in the decorator
 * config overrides the generated one.
 *
 * For the MCP endpoint to actually be served, you must call
 * {@link McpAdaptor.upgrade} on the {@link INestApplication} instance at
 * bootstrap. The decorator alone only stores reflection metadata.
 *
 * @example
 * ```typescript
 * import core from "@nestia/core";
 *
 * @Controller()
 * export class WeatherController {
 *   @core.McpRoute({
 *     name: "get_weather",
 *     description: "Return current weather for a city.",
 *   })
 *   public async get(
 *     @core.McpRoute.Params() params: { city: string },
 *   ): Promise<{ temp: number }> {
 *     return { temp: 22 };
 *   }
 * }
 * ```
 *
 * @param config Tool configuration (name, description, optional overrides).
 * @returns Method decorator.
 * @author wildduck - https://github.com/wildduck2
 */
export function McpRoute(config: McpRoute.IConfig): MethodDecorator {
  return function McpRoute(
    _target: Object,
    _propertyKey: string | symbol,
    descriptor: TypedPropertyDescriptor<any>,
  ): TypedPropertyDescriptor<any> {
    Reflect.defineMetadata(
      "nestia/McpRoute",
      {
        name: config.name,
        title: config.title,
        description: config.description,
        inputSchema: config.inputSchema ?? { type: "object", properties: {} },
        outputSchema: config.outputSchema,
        annotations: config.annotations,
      } satisfies IMcpRouteReflect,
      descriptor.value,
    );
    return descriptor;
  };
}

export namespace McpRoute {
  /**
   * Configuration passed to {@link McpRoute}.
   *
   * All optional schemas (`inputSchema`, `outputSchema`) are auto-generated
   * from TypeScript types via the nestia transformer when omitted; supply
   * them explicitly only to override the compile-time inference.
   */
  export interface IConfig {
    /**
     * Unique tool identifier reported in `tools/list` responses and used by
     * the MCP client to invoke this tool via `tools/call`.
     */
    name: string;

    /**
     * Human-readable display name shown in MCP client UIs.
     */
    title?: string;

    /**
     * Free-form description consumed by the LLM when deciding whether to
     * call this tool. Include expected inputs, side effects, and typical
     * usage — the quality of this text strongly affects tool-selection
     * accuracy.
     */
    description?: string;

    /**
     * JSON Schema (draft 2020-12) for the tool's input.
     *
     * Auto-generated by the transformer from the `@McpRoute.Params<T>()`
     * parameter type when omitted.
     */
    inputSchema?: object;

    /**
     * JSON Schema for structured tool output. When present, the MCP client
     * may validate returned `structuredContent` against this schema.
     */
    outputSchema?: object;

    /**
     * Tool behavior hints used by MCP clients to render safety cues and
     * decide when to auto-approve calls.
     */
    annotations?: IMcpRouteReflect["annotations"];
  }

  /**
   * Parameter decorator for an MCP tool's input arguments.
   *
   * `@McpRoute.Params<T>()` validates the `arguments` object from a
   * `tools/call` request against the TypeScript type `T` using typia. A
   * failed validation surfaces to the client as a JSON-RPC `-32602`
   * (`InvalidParams`) error with structured diagnostics, giving the LLM
   * precise feedback to self-correct.
   *
   * At most one parameter per method should carry this decorator — the MCP
   * spec models tool input as a single arguments object.
   *
   * @param validator Optional custom validator. Default is `typia.assert()`.
   * @returns Parameter decorator.
   * @author wildduck - https://github.com/wildduck2
   */
  export function Params<T>(
    validator?: IRequestBodyValidator<T>,
  ): ParameterDecorator {
    const validate = validate_request_body("McpRoute.Params")(validator);
    return function McpRouteParams(
      target: Object,
      propertyKey: string | symbol | undefined,
      parameterIndex: number,
    ) {
      emplace(target, propertyKey ?? "", {
        category: "params",
        index: parameterIndex,
        validate,
      });
    };
  }

  /** @internal */
  const emplace = (
    target: Object,
    propertyKey: string | symbol,
    value: IMcpRouteReflect.IArgument,
  ) => {
    const array: IMcpRouteReflect.IArgument[] | undefined = Reflect.getMetadata(
      "nestia/McpRoute/Parameters",
      target,
      propertyKey,
    );
    if (array !== undefined) array.push(value);
    else
      Reflect.defineMetadata(
        "nestia/McpRoute/Parameters",
        [value],
        target,
        propertyKey,
      );
  };
}
