/**
 * @module api.functional.v2
 * @packageDocumentation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as bbs from "./bbs";
