import type { RecordstringIJsonComponents } from "./RecordstringIJsonComponents";
import type { RecordstringISwaggerSecurityScheme } from "./RecordstringISwaggerSecurityScheme";

/**
 * Reusable components in Swagger.
 *
 * `ISwaggerComponents` is a data structure representing content of `components` object
 * in `swagger.json` file generated by Nestia. Note that, this is not an universal
 * structure, but a dedicated structure only for Nestia.
 *
 * @author Jeongho Nam - https://github.com/samchon
 */
export type ISwaggerComponents =
  /**
   * Reusable components in Swagger.
   *
   * `ISwaggerComponents` is a data structure representing content of `components` object
   * in `swagger.json` file generated by Nestia. Note that, this is not an universal
   * structure, but a dedicated structure only for Nestia.
   *
   * @author Jeongho Nam - https://github.com/samchon
   */
  {
    /**
     * An object to hold reusable DTO schemas.
     *
     * For reference, `nestia` stores every object and alias types as reusable DTO
     * schemas. The alias type means that defined by `type` keyword in TypeScript.
     */
    schemas?: undefined | RecordstringIJsonComponents.IAlias;
    /**
     * An object to hold reusable security schemes.
     *
     * This property be configured by user in `nestia.config.ts` file.
     */
    securitySchemes?: undefined | RecordstringISwaggerSecurityScheme;
  };
