/**
 * @packageDocumentation
 * @module api.functional.healthy
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

export * as alive from "./alive";

/**
 * @controller HealthController.check()
 * @path GET /healthy/check
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function check
    (
        connection: IConnection
    ): Promise<void>
{
    return Fetcher.fetch
    (
        connection,
        check.ENCRYPTED,
        check.METHOD,
        check.path()
    );
}
export namespace check
{

    export const METHOD = "GET" as const;
    export const PATH: string = "/healthy/check";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/healthy/check`;
    }
}