name: build
on: 
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'config/**'
      - 'packages/*/native/**'
      - 'packages/*/src/**'
      - 'packages/*/package.json'
      - 'packages/*/tsconfig.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: packages/core/native/go.mod
          cache-dependency-path: packages/core/native/go.sum

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm build
