name: format
on:
  pull_request:
    paths:
      - '.github/workflows/format.yml'
      - '.prettierignore'
      - 'prettier.config.js'
      - '.gitattributes'
      - 'packages/**/*.ts'
      - 'tests/**/*.ts'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Check Formatting
        run: pnpm run format:check
